### ISSUE TITLE
Autocomplete not readable

### ISSUE THREAD

**Issue by neversun** [bubersson/hop-theme-vscode#1]
A recent update of VSCode changed something with the autocompletion highlighting.
Since then, the autocomplete is not readable any more (dark blue text on blue background).

This happens to be an issue with both `Hop Light` and `Hop Light (italics)` theme.

`Hop Light (italics) - Javascript`
![js](https://user-images.githubusercontent.com/9157500/123410204-552df380-d5af-11eb-87a5-ad6f8982a256.jpg)

`Hop Light (italics) - Menu`
![menu](https://user-images.githubusercontent.com/9157500/123410205-55c68a00-d5af-11eb-8a3c-2f73649cae96.jpg)

**Comment by ddanger** [comment]
I just noticed this too. Was surprised this theme hasn't been updated for so long.

I could switch to default light ... but HTML colors are pretty ugly.

**Comment by wnipun** [comment]
I use the following code on settings.json to modify the highlight colours.

`
"[Hop Light]": {
        "editorSuggestWidget.focusHighlightForeground": "#ffffff",
        "list.focusHighlightForeground": "#ffffff"
      }
`

**Comment by bubersson** [comment]
Nice! Would you be able to send a PR for this change in the theme? I can then update it in the store

**Comment by bezvoshchuk** [comment]
I was just about to create the same issue. 
Nice that this theme needs only one input in 4 years :) 

@nipun5perera please go with PR.

**Comment by timkgh** [comment]
> I use the following code on settings.json to modify the highlight colours.
> 
> `"[Hop Light]": { "editorSuggestWidget.focusHighlightForeground": "#ffffff", "list.focusHighlightForeground": "#ffffff" }`

Tried it but it doesn't appear to work. I added it to `$HOME/Library/Application Support/Code/User/settings.json`

@bubersson would you be able to fix the theme please?

**Comment by simleb** [comment]
As for the temporary fix to `settings.json`, it need to be wrapped in `workbench.colorCustomizations`:
```json
"workbench.colorCustomizations": {
    "[Hop Light]": {
        "editorSuggestWidget.focusHighlightForeground": "#d4e0ff",
        "list.focusHighlightForeground": "#d4e0ff"
    }
}
```
